source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               lib/commons-csv-1.12.0.jar,\
               lib/commons-io-2.17.0.jar,\
               lib/commons-codec-1.17.1.jar
